use std::collections::HashSet;
use std::error::Error;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use tracing::info;

use crate::jsoncanvas::NodeId;

/// TOML structure for the tracker file
#[derive(Debug, Serialize, Deserialize)]
pub struct TrackerFile {
    pub published_node_ids: Vec<String>,
}

/// Tracks which nodes have been published to a specific sink
pub struct SyndicationTracker {
    /// Path to the TOML tracker file
    path: PathBuf,
    /// In-memory set of published node IDs for O(1) lookup
    published_ids: HashSet<String>,
}

impl SyndicationTracker {
    /// Create a tracker for a canvas file and sink combination
    ///
    /// File naming: `.<canvas-name>.canvas.syndication.<sink-name>.toml`
    pub fn new(canvas_path: &Path, sink_name: &str) -> Result<Self, Box<dyn Error>> {
        let canvas_dir = canvas_path.parent().ok_or("Canvas path has no parent directory")?;
        let canvas_filename = canvas_path
            .file_name()
            .and_then(|s| s.to_str())
            .ok_or("Invalid canvas filename")?;

        // Build tracker filename: .<canvas-name>.syndication.<sink-name>.toml
        let tracker_filename = format!(".{}.syndication.{}.toml", canvas_filename, sink_name);
        let path = canvas_dir.join(tracker_filename);

        // Load existing tracker or create empty
        let published_ids = if path.exists() {
            let content = std::fs::read_to_string(&path)?;
            let tracker: TrackerFile = toml::from_str(&content)?;
            tracker.published_node_ids.into_iter().collect()
        } else {
            HashSet::new()
        };

        info!(tracker_path = %path.display(), published_count = published_ids.len(), "Loaded tracker");

        Ok(Self { path, published_ids })
    }

    /// Check if a node has already been published
    pub fn is_published(&self, node_id: &NodeId) -> bool {
        self.published_ids.contains(node_id.as_str())
    }

    /// Mark nodes as published and save to disk
    pub fn mark_published(&mut self, node_ids: &[NodeId]) -> Result<(), Box<dyn Error>> {
        if node_ids.is_empty() {
            return Ok(());
        }

        for node_id in node_ids {
            self.published_ids.insert(node_id.as_str().to_string());
        }

        let tracker = TrackerFile {
            published_node_ids: self.published_ids.iter().cloned().collect(),
        };

        let toml_content = toml::to_string_pretty(&tracker)?;
        let content_with_header = format!(
            "# Generated by syndicate-json-canvas - Do not edit manually\n\n{}",
            toml_content
        );

        std::fs::write(&self.path, content_with_header)?;
        info!(tracker_path = %self.path.display(), total_published = self.published_ids.len(), "Saved tracker");

        Ok(())
    }
}
